# site settings
title: SUKANYA
subtitle:
email: workwithuusmai@gmail.com
description: It’s my portfolio here
baseurl: "" # the subpath of your site, e.g. /blog
url: https://uusmai.github.io # the base hostname & protocol for your site
phone: +66 86354 2644

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram: https://instagram.com/uusmai?utm_medium=copy_link
  LinkedIn: https://th.linkedin.com/in/sukanya-saysud-184017157
  Twitter:
  Facebook:
  Slack:
  Youtube: https://youtube.com/channel/UCLnFlYUEYBgq0_RAFfEGncA

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
